services:
  - type: web
    name: blog-api
    runtime: node
    plan: free
    buildCommand: pwd && npm ci && npm run build && ls -la && ls -la dist/
    startCommand: pwd && cd .. && pwd && ls -la && node --no-warnings dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_JWKS_URL
        sync: false
      - key: PORT
        value: 5173
    healthCheckPath: /health
